---
### Global vars ###
fabric_asn: 65000
mtu: 9216

### L2VNI vars ###
net_name: mynetwork_10101
net_vlan: 101
net_vni: 10101
net_mgroup: 225.1.2.3
net_subnet: 10.0.1.254/24
net_is_l3: true

### L3VNI vars ###
vrf_name: myvrf_10000
vrf_vlan: 3000
vrf_vni: 13000

### access port vars ###
access_ports:
  - Ethernet1/1
port_mode: access # can be either 'access' or 'trunk'
port_desc: "*** access port - test Ansible ***"