---
- name: Build ACI tenant
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/creds.yml
    - vars/tenant_vars.yml

  tasks:
  - name: Build ACI tenant and import AVI logical device
    aci_rest:
      hostname: "{{ apic_ip }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      use_ssl: no
      validate_certs: no
      path: /api/mo/uni.xml
      method: post
      content: |
        <fvTenant name="{{ Tenant }}">

          <fvCtx name="{{ vrf }}"/>

          <fvBD name="{{ bd_1 }}">
            <fvSubnet ip="{{ bd_1_ip }}"/>
            <fvRsCtx tnFvCtxName="{{ vrf }}"/>
          </fvBD>

          <vzFilter name="Http-Filter">
            <vzEntry name="Http-Port" dFromPort="80" dToPort="80" etherT="ip" prot="6"/>
          </vzFilter>
          <vzFilter name="Ping-Filter">
            <vzEntry name="ICMP" etherT="ip" prot="icmp"/>
          </vzFilter>

          <vzBrCP name="{{ Contract }}">
            <vzSubj name="{{ subj_default }}">
              <vzRsSubjFiltAtt tnVzFilterName="Http-Filter"/>
              <vzRsSubjFiltAtt tnVzFilterName="Ping-Filter"/>
            </vzSubj>
          </vzBrCP>

          <fvAp name="{{ AppProfile }}">
            <fvAEPg name="{{ ClientEPG }}">
              <fvRsDomAtt tDn="uni/vmmp-VMware/dom-{{ apic_VMM }}" instrImedcy="immediate" resImedcy="immediate"/>
              <fvRsBd tnFvBDName="{{ bd_1 }}"/>
              <fvRsCons tnVzBrCPName="{{ Contract }}"/>
            </fvAEPg>
            <fvAEPg name="{{ ServerEPG }}">
              <fvRsDomAtt tDn="uni/vmmp-VMware/dom-{{ apic_VMM }}" instrImedcy="immediate" resImedcy="immediate"/>
              <fvRsBd tnFvBDName="{{ bd_1 }}"/>
              <fvRsProv tnVzBrCPName="{{ Contract }}"/>
            </fvAEPg>
          </fvAp>

          <vnsLDevIf ldev="uni/tn-common/lDevVip-{{ avi_device }}"/>

        </fvTenant>
        
    delegate_to: localhost