---
- name: Clean the demo
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/creds.yml
    - vars/tenant_vars.yml

  tasks:

# Detach VMs from ACI created Port-Groups
  - name: Detach front-end VMs from ACI PGs
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      datacenter: "{{ vcenter_dc }}"
      folder: "{{ vcenter_vm_folder }}"
      state: present
      networks:
      - name: "VM Network"
    with_items:
      - "{{ Frontend_1 }}"
    delegate_to: localhost

  - name: Detach back-end VMs from ACI PGs
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      datacenter: "{{ vcenter_dc }}"
      folder: "{{ vcenter_vm_folder }}"
      state: present
      networks:
      - name: "VM Network"
    with_items:
      - "{{ Backend_1 }}"
      - "{{ Backend_2 }}"
      - "{{ Backend_3 }}"
    delegate_to: localhost

# Pause to make sure VMs had been detached before clearing the Distribued Port-Groups
  - pause:
      seconds: 5
      prompt: "Pause to make sure VMs had been detached before deleting the Distribued Port-Groups"

# Delete ACI Tenant
  - name: Delete ACI Tenant
    aci_rest:
      hostname: "{{ apic_ip }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      use_ssl: no
      validate_certs: no
      path: /api/mo/uni.xml
      method: post
      content: |
        <fvTenant name="{{ Tenant }}" status="deleted">
        </fvTenant>
    delegate_to: localhost
